### ISSUE TITLE
missing lib files?

### ISSUE THREAD

**Issue by ghost** [githuntio/extension#1]
i cloned the repo and tried to load the unpacked extension, but the js files in the lib directory appear to be missing.

specifically, these three

```
            "lib/jquery/dist/jquery.js",
            "lib/moment/min/moment-with-locales.js",
            "lib/uri.js/src/URI.js"
```

I would like to try out the extension, so let me know if I'm missing something, thanks

**Comment by egoist** [comment]
You missed nothing, could u show me what error you exactly caught?
